# Generated by Django 6.0 on 2025-12-21 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='产品名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('category', models.CharField(choices=[('electronics', '电子产品'), ('clothing', '服装'), ('food', '食品'), ('tools', '工具'), ('other', '其他')], default='other', max_length=50, verbose_name='类别')),
                ('quantity', models.IntegerField(default=0, verbose_name='库存数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('location', models.CharField(max_length=100, verbose_name='存放位置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
                'permissions': [('can_view_product', '可以查看产品'), ('can_add_product', '可以添加产品'), ('can_change_product', '可以修改产品'), ('can_delete_product', '可以删除产品'), ('can_search_product', '可以搜索产品')],
            },
        ),
    ]
